### ISSUE TITLE
About rxandroidble version

### ISSUE THREAD

**Issue by hanabi1224** [Polidea/MultiPlatformBleAdapter#41]
Hello, I notice this library is currently using com.polidea.rxandroidble:rxandroidble:1.7.0 which was released a year ago, is there plan to upgrade to com.polidea.rxandroidble2 with latest changes?  Thanks!

**Comment by mikolak** [comment]
Hi @hanabi1224 !

I've talked to @dariuszseweryn and IIRC introducing RxAndroidBLE 2 would break the library. Are there any specific changes you need?

**Comment by hanabi1224** [comment]
@mikolak Ah not really, my project is currently using flutter_blue and I'm investigating whether `FlutterBleLib` is a better solution.   A stale dependency with no upgrade path/plan seems to be a risk tho

**Comment by dariuszseweryn** [comment]
I have plans for changing `RxAndroidBle` API so it will be possible to fully encapsulate `RxJava2` so it could be an implementation detail (which is currently a problem due to `RxJava2` design decisions)

**Comment by hanabi1224** [comment]
@dariuszseweryn Awesome, looking forward to that!

**Comment by robwalkerco** [comment]
Hi @dariuszseweryn and @mikolak 

I seem to be running into the issue fixed in RxAndroidBle 1.10.5-rxjava2 (https://github.com/Polidea/RxAndroidBle/pull/639) 

I'm using react-native-ble-plx, but it looks like that will soon be updated to use the library, and so whatever version of RxAndroidBle this library uses.

The issue I'm seeing is that when getting a large number of characteristic notifications very close together, I'm receiving the notifications out of order.

Does it sound like the issue I'm having is the same as was resolved in the Polidea/RxAndroidBle#639 ? And is that any estimation on when the RxAndroidBleversion may be updated in either this library or react-native-ble-plx?

Thanks for your help and for your brilliant BLE libraries :)

**Comment by JamesMcIntosh** [comment]
Hi @dariuszseweryn & @mikolak,
I see that you are no longer actively developing the RxAndroidBle RxJava1 branch.
RxJava1 was end of life 2.5 years ago, shouldn't it be reasonable to make a legacy branch for RxJava1 support in this repository and make the master branch RxJava2 and bump the version to 2.x?
Thanks James

**Comment by JamesMcIntosh** [comment]
Hi @dariuszseweryn & @mikolak,
I've submitted a pull request #67 which migrates to RxJava2
Kind regards
James

**Comment by JamesMcIntosh** [comment]
> Hi @hanabi1224 !
> 
> I've talked to @dariuszseweryn and IIRC introducing RxAndroidBLE 2 would break the libraries using this one. Are there any specific changes you need?

I have updated the version of MultiPlatformBleAdapter in FlutterBleLibPlugin without having to change a line of code as the MultiPlatformBleAdapter API is built around callbacks which hide the RxJava implementation from view. (nice work!)
I would therefore expect other clients to be able to be updated without much issue unless they depend on the transitive dependency of RxJava1.

**Comment by JamesMcIntosh** [comment]
@hanabi1224 RxJava2 branch is now available
https://github.com/Polidea/MultiPlatformBleAdapter/tree/beta/rxandroible2

@mikolak close the issue?

**Comment by mikolak** [comment]
Yeah. Man, we really need more manpower here, I completely forgot this issue existed at all...
